print("Hello world!")
print("-")
print("This is all I want")
print("Nothing else")
print("I want to test stuff")
print("Without having to deploy 300MB of useless code")
print("Just a simple file")
print("With some tests on it")
print("-")
print("Thanks.")
